from avltree import *
from algo1 import *

AT=AVLTree()
avl_insert(AT,"10",10)
avl_insert(AT,"5",5)
avl_insert(AT,"20",20)
avl_insert(AT,"1",1)
avl_insert(AT,"6",6)
BT=AVLTree()
avl_insert(BT,"100",100)
avl_insert(BT,"50",50)
avl_insert(BT,"120",120)
avl_insert(BT,"45",45)
avl_insert(BT,"60",60)
avl_insert(BT,"140",140)
imprimirarbol(AT,AT.root)
imprimirarbol(BT,BT.root)
tree= A_X_B(AT,40,BT)
imprimirarbol(tree,tree.root)
#calculoBF(AT)
# rotateRight(AT,AT.root)
# calculoBF(AT)